server:
  port: 8085
spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:8090/postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    generate-ddl: true
  web:
    resources:
      static-locations: classpath:/spring-frontend/
  thymeleaf:
    prefix: classpath:/spring-frontend/
  sql:
    init:
      data-locations: classpath:authors.sql, classpath:books.sql, classpath:book2author.sql
      mode: never
  messages:
    basename: lang.messages, lang.mainpage
  liquibase:
    enabled: true
    change-log: classpath:/db.changelog/db.changelog-master.xml
