server:
  port: 8085
spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:8090/postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    generate-ddl: true
  web:
    resources:
      static-locations: classpath:/spring-frontend/
  thymeleaf:
    prefix: classpath:/spring-frontend/
  sql:
    init:
      data-locations: classpath:users.sql, classpath:tags.sql, classpath:genres.sql, classpath:books.sql, classpath:authors.sql, classpath:balance_transaction.sql, classpath:book2user_type.sql, classpath:book2user.sql, classpath:book2tag.sql, classpath:book2genre.sql, classpath:book2author.sql
      mode: never
  messages:
    basename: lang.messages, lang.mainpage
  liquibase:
    enabled: true
    change-log: classpath:/db.changelogs/db.changelog-master.xml
  jackson:
    serialization:
      fail-on-empty-beans: false
springdoc:
  swagger-ui:
    path: /swagger-ui.html

